const CACHE_NAME = 'pocketbank-v6';
const ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './css/styles.css',
  './js/firebase-config.js',
  './js/firebase-service.js',
  './js/family-service.js',
  './js/kids-service.js',
  './js/transactions-service.js',
  './js/sync-service.js',
  './js/family-setup.js',
  './js/auth.js',
  './js/utils.js',
  './js/store.js',
  './js/backup.js',
  './js/export.js',
  './js/views.js',
  './js/app.js',
  './js/sw-register.js',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/favicon-32.png'
];
